### PR TITLE
Update Dockerfile

### PR DESCRIPTION
**Pull request by MaPhani**

### CODE REVIEW

**Comment by MaPhani** [comment]
commit tthe file

**Comment by MaPhani** [comment]
ss

**Comment by MaPhani** [comment]
commit

**Comment by mjstealey** [comment]
Underlying `LTS` image is Ubuntu/Debian based, not RHEL/CentOS based, so `apt` is used, not `yum` 
- You are welcome to fork and change the base to be a RHEL/CentOS image and maintain separately
- I prefer to stick with Ubuntu/Debian here

Provenance: The work here uses this [Base image](https://github.com/jenkinsci/docker/blob/master/11/debian/bullseye/hotspot/Dockerfile) which is derived from this [Source image](https://github.com/adoptium/containers/blob/5bd9771ac01651e79894552b66e4007f2501316b/11/jdk/ubuntu/Dockerfile.releases.full)

**Pull request closed without merging**
